### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by miere** [netlify/aws-lambda-rust-runtime#9]
As mentioned earlier in [a different issue](https://github.com/awslabs/aws-lambda-rust-runtime/issues/267), enabling discussions in this repository would be a good way to define development strategies for this project.

I'm keen to help this repository to thrive and listen to the community feedback on might be introduced from this fork. I'm especially curious to hear the thoughts of @nmoutschen (who works at AWS) and @softprops (who've dedicated several hours on the current design).

**Comment by softprops** [comment]
+1.

In the past discord and other mediums served a similar purpose but to me have always felt disjoint from the hub of projects, the GitHub repo. One might argue that affords freedoms like more easily moving away from GitHub. In most cases that seems like a premature optimization for an unlikely to future state.

GitHub discussions seems purpose built for this kind of dialogue, dialogue about the project and less about specific piece of code itself

**Comment by calavera** [comment]
Enabled! 🙌 https://github.com/netlify/aws-lambda-rust-runtime/discussions
